name: Deploy Lambda - Parse Filename

on:
  push:
    branches:
      - main
    paths:
      - "lambda/parse_filename/**"
      - ".github/workflows/deploy-lambda.yml"

  # allows you to run manually from GitHub Actions UI
  workflow_dispatch: {}

permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Debug step: helps us validate branch/ref used by the token (very important for trust policy)
      - name: Show GitHub context (debug)
        run: |
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME"

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::756118984406:role/Role-GitHubActions-Deploy
          aws-region: ap-southeast-2

      # Debug step: confirms role assumption worked
      - name: Verify AWS identity (debug)
        run: aws sts get-caller-identity

      - name: Create Lambda zip (only lambda_function.py)
        run: |
          cd lambda/parse_filename
          zip -r function.zip lambda_function.py

      - name: Deploy Lambda code
        run: |
          aws lambda update-function-code \
            --function-name lambda-parse-account-filename \
            --zip-file fileb://lambda/parse_filename/function.zip \
            --region ap-southeast-2