name: Deploy Lambda - Parse Filename

on:
  push:
    branches: [ "main" ]
    paths:
      - "lambda/parse_filename/**"
      - ".github/workflows/deploy-lambda.yml"
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::756118984406:role/Role-GitHubActions-Deploy
          aws-region: ap-southeast-2

      - name: Deploy Lambda Function
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: lambda-parse-account-filename
          code-artifacts-dir: lambda/parse_filename